volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: wasiliy/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - db
  frontend:
    image: wasiliy/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
    depends_on:
      - backend
  gateway:
    image: wasiliy/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - backend
      - frontend
